### ISSUE TITLE
WinPhone Namespace incorrect

### ISSUE THREAD

**Issue by dsacharny** [oxyplot/documentation-examples#1]
Hello,

Looks like the line should really be:

OxyPlot.Xamarin.Forms.Platform.WP8.Forms.Init();

 - "WinPhone" is not a namespace in the forms code, "WP8" is however.

**Comment by objorke** [comment]
Thanks I have updated the OxyPlot packages, see https://github.com/oxyplot/documentation-examples/commit/804d581860a641ab27bf71693cd34aa863d6ab8a
